### PR TITLE
fix: add gpt version in query

### LINKED ISSUE #248: Add `gptVersion` to select model in query param in chatbot hook

### PR DESCRIPTION
**Pull request by spaenleh**
In this PR I add the possibility to request a specific gpt version when using the hook.

close #248

### CODE REVIEW

File: src/mutations/chatBot.ts [hunk 1]
```diff
@@ -10,14 +10,15 @@ import { QueryClientConfig } from '../types';
 export default (queryConfig: QueryClientConfig) => {
   const { notifier } = queryConfig;
 
-  const usePostChatBot = () => {
+  // TODO: should use enum from the backend ?
```
Comment (ReidyT) [inline src/mutations/chatBot.ts:13]: Yes I think it could be interesting to have it in SDK for example ? With that we have only one place to change if we decide to add a new version ?

**Review by ReidyT — APPROVED** [review]
Thanks for this PR ! LGTM 👍

**Review by ReidyT — COMMENTED** [review]
Thanks for this change 😆
